name = "PoolQueues"
uuid = "da57cb61-2122-4cb9-bf56-fd6f75f7b468"
authors = ["David MacMahon <davidm@astro.berkeley.edu> and contributors"]
version = "0.4.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
